name: Playwright Tests
on:
  schedule:
    - cron: '30 8 * * *'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install pdm
        pdm install
    - name: Ensure browsers are installed
      run: pdm run playwright install --with-deps
    - name: Run your tests
      run: pdm run src/example_test.py
